version: '3.8'
services:
  jenkins:
    image: myjenkins-blueocean:2.452.2-1
    container_name: jenkins
    networks:
      - jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins/jenkins-docker-certs:/certs/client:ro

  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    networks:
      - jenkins
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - ./jenkins/jenkins-docker-certs:/certs/client
    ports:
      - "2376:2376"
    command: ["--storage-driver", "overlay2"]

networks:
  jenkins:
